server:
  port: 8889

spring:
  application:
    name: config2
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, refresh